# -*- coding: utf-8 -*-
#
# Copyright (C) 2024 Graz University of Technology.
#
# Invenio-override is free software; you can redistribute it and/or modify
# it under the terms of the MIT License; see LICENSE file for more details.

name: i18n:extract translations
on: workflow_dispatch
permissions:
  contents: write
  pull-requests: write

jobs:
  i18n-extract:
    runs-on: ubuntu-20.04
    env:
      PYTHON-VERSION: 3.12
      NODE-VERSION: 14.x
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # setup python
      - name: Set up Python ${{ env.PYTHON-VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON-VERSION }}

      # install dependencies
      - name: Install dependencies
        run: |
          pip install -e ".[tests,opensearch2]"

      # extract backend messages
      - name: Extract backend messages & update .po changes
        run: |
          python setup.py extract_messages
          python setup.py update_catalog -l en
          python setup.py update_catalog -l de

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: i18n:extract translations
          title: i18n:extract translations
          body: i18n:extract translations
          branch: 101-translations-extract # name of branch which PR is created from
          delete-branch: true # delete branch once merged,closed
